# Numpy _ Part 2

In [1]:
import numpy as np

### 4. Operation

In [2]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [3]:
# 모든 요소들(elements)의 합
a.sum()

78

In [4]:
# 열의 합
a.sum(axis=0)

array([15, 18, 21, 24])

In [5]:
# 행의 합
a.sum(axis=1)

array([10, 26, 42])

In [6]:
np.sum(a[0])

10

In [7]:
np.sum(a[1])

26

In [8]:
a.min(axis=0)

array([1, 2, 3, 4])

In [9]:
a.max(axis=1)

array([ 4,  8, 12])

In [10]:
a.mean()

6.5

In [11]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- sorting

In [13]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [14]:
np.sort(b)      # axis = 1 (행단위로 변함), ascending order  ==> default 값

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [15]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [17]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [18]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [19]:
# 내림차순
c = np.array([43, 38, 12, 25])
np.sort(c)[::-1]

array([43, 38, 25, 12])

In [20]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [21]:
c[[2,3,1,0]]

array([12, 25, 38, 43])

In [22]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 43])

- Mathematical functions

In [23]:
# sigmoid 함수
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [24]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [25]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [26]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

In [27]:
# 전치(T / Transpose) ==> 행/열을 열/행으로 뒤바꿈 !

- concatenate, vstack, hstack

In [28]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [29]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [31]:
np.vstack((a,b))    # vertical

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.concatenate((a,b), axis=0)       # array를 합치는 친구들 ==> concatenate / vstack / hstack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.hstack((a, b.T))   # horizontal

array([[1, 2, 5],
       [3, 4, 6]])

In [36]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 5. Array Operation

- 사칙연산

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a + a

array([[2, 4],
       [6, 8]])

In [39]:
a - a

array([[0, 0],
       [0, 0]])

In [40]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [41]:
a / a

array([[1., 1.],
       [1., 1.]])

- Broadcasting

In [42]:
a + 3

array([[4, 5],
       [6, 7]])

- Dot product

In [44]:
a = np.arange(1,7).reshape(2,3)     # matrix 곱셈 / 2차원 이상일 경우 (l,m) x (m,n) ==> (l,n)
b = np.arange(7,13).reshape(3,2)    

In [45]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [46]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [47]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### 6. Comparison

- all & any

In [48]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a > 5       # filtering

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [50]:
np.any(a>5)     # ~중에 하나라도 조건을 만족하는가? --> 하나라도 True가 있으면 True

True

In [51]:
np.all(a>5)     # ~중에 모두가 조건을 만족하는가? --> 모두(all)가 True여야 True

False

- Logical operation

In [52]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [53]:
np.logical_or(a > 7, a < 3)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [55]:
a.argmax(), np.argmax(a)    # argmin ==> array 내 최대값 index 리턴

(9, 9)

In [56]:
a.argmin(), np.argmin(a)    # argmax ==> array 내 최소값 index 리턴 

(0, 0)

### 7. Boolean & Fancy indexing

- boolean indexing

In [57]:
# array 'a' 에서 값이 6 이상인 것만 가져오기 --> filtering
a[a >= 6]

array([6, 7, 8, 9])

In [58]:
a >= 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [59]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [60]:
a[b]

array([4, 5, 6])

- fancy indexing

In [61]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])     # a의 인덱스값
a[b]

array([2, 2, 4, 8, 6, 4])

### 8. 기술 통계

In [62]:
a = np.random.randn(10)
a

array([ 2.03202251, -0.145975  , -0.09617814, -0.55921655, -0.18091137,
       -1.96196362, -0.49547983,  1.287721  ,  0.19095987, -1.04733846])

In [63]:
# 평균
np.mean(a), a.mean()

(-0.09763595954721256, -0.09763595954721256)

In [64]:
# 표준편차(standard deviation)
np.std(a), a.std()

(1.0628362567421754, 1.0628362567421754)

In [65]:
# 최소, 최대
a.min(), a.max()

(-1.9619636201472772, 2.0320225100218283)

In [67]:
# 4분위수
np.percentile(a,25), np.percentile(a,50), np.percentile(a,75)       # 1사분위수 / 2사분위수(중앙값) / 3사분위수

(-0.5432823713383053, -0.16344318102561106, 0.11917536715755699)

In [68]:
# 중앙값
np.median(a)

-0.16344318102561106

In [70]:
a = np.random.randint(0,3,100)
a

array([1, 0, 2, 1, 2, 0, 2, 2, 2, 1, 0, 1, 2, 1, 2, 0, 0, 2, 1, 0, 0, 2,
       1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0,
       2, 2, 1, 0, 1, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0,
       2, 2, 2, 1, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0,
       1, 0, 1, 1, 2, 0, 0, 0, 0, 0, 1, 2])

In [71]:
# 0, 1, 2 의 갯수
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([33, 34, 33], dtype=int64))