# Numpy - 연습 문제   
    (답은 왠만하면 한 줄로...!)

1. 넘파이를 사용해 다음과 같은 행렬을 만드시오.    
    <pre>
    10 20 30 40
    50 60 70 80

In [2]:
import numpy as np

In [5]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2. 다음 행렬과 같은 행렬이 있다.

In [8]:
m = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# 1) 이 행렬에서 값 7을 인덱싱한다.
m[1,2]

7

In [10]:
# 2) 이 행렬에서 값 14를 인덱싱한다.
m[2,-1]

14

In [12]:
# 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱 한다.
m[1, 1:3]

array([6, 7])

In [13]:
# 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱 한다.
m[1:3, 2]

array([ 7, 12])

In [15]:
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱 한다.
m[0:2, -2:]

array([[3, 4],
       [8, 9]])

3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제를 푸시오.

In [62]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
# 1) 이 배열에서 3의 배수를 찾아라.
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [19]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [22]:
f[(f%3==0) & (f%4==1)]

array([9])

4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
    <pre>
    2, 1, 0, 0, 0
    3, 2, 1, 0, 0
    0, 3, 2, 1, 0
    0, 0, 3, 2, 1
    0, 0, 0, 3, 2

In [34]:
ar = np.arange(3, -1, -1)
ar

array([3, 2, 1, 0])

5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

In [40]:
a_rand = np.random.uniform(0, 10, 30).reshape(5,6)
a_rand

array([[8.24273822, 2.49067835, 4.81493172, 3.57360324, 0.94626005,
        5.79567381],
       [8.66206238, 1.39645018, 5.59520584, 3.17249193, 4.31179242,
        5.27945711],
       [9.45791046, 5.47722088, 3.85194931, 7.02280315, 0.85190638,
        3.81737843],
       [8.69741309, 3.42222974, 0.0939424 , 7.54708889, 9.58322922,
        5.03544792],
       [8.81434105, 7.15814987, 1.38365994, 4.1954721 , 7.12219511,
        9.91267643]])

In [43]:
# 1) 전체의 최댓값
a_rand.max()

9.912676431604648

In [44]:
# 2) 각 행의 합
a_rand.sum(axis=1)

array([25.86388538, 28.41745986, 30.47916862, 34.37935126, 38.5864945 ])

In [47]:
# 3) 각 행의 최댓값
a_rand.max(axis=1)

array([8.24273822, 8.66206238, 9.45791046, 9.58322922, 9.91267643])

In [48]:
# 4) 각 열의 평균
a_rand.mean(axis=0)

array([8.77489304, 3.9889458 , 3.14793784, 5.10229186, 4.56307664,
       5.96812674])

In [49]:
# 5) 각 열의 최솟값
a_rand.min(axis=0)

array([8.24273822, 1.39645018, 0.0939424 , 3.17249193, 0.85190638,
       3.81737843])

6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다.   
영어 성적을 기준으로 각 열(column)을 재정렬하시오.
<pre>
    array([[1, 2, 3, 4],
        [46, 99, 100, 71],
        [81, 59, 90, 100]])

In [3]:
score = np.array([[1, 2, 3, 4],     # 학번
        [46, 99, 100, 71],          # 영어성적
        [81, 59, 90, 100]])         # 수학성적
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [57]:
Eng_score = score[:, score[1,:].argsort()]
Eng_score

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

-  강사님 해설 및 정답

In [ ]:
# 영어 성적을 기준으로 다른 행을 바꿀 것이기 때문에, argsort() !
# 첨부터 너무 한 줄로만 만드려고 하지 말고, 일단 풀어서 써 볼 것

In [4]:
# 영어 성적을 argsort()
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [5]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [6]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [7]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [ ]:
# 강사님 해답 -> seed(2022)로 지정해서 하셨음 !

In [9]:
ex = np.random.randint(1, 7, size=100)
print(ex)
ex.mean()

[2 6 1 5 4 5 2 3 4 2 4 3 1 3 6 4 4 4 5 5 5 4 1 5 6 4 5 4 1 2 1 1 6 2 6 2 1
 3 5 1 3 5 1 6 6 6 3 6 5 6 1 5 4 4 2 2 3 6 3 4 5 5 4 2 1 5 4 3 3 1 4 2 2 5
 5 1 3 4 3 3 2 2 5 6 2 4 6 1 5 6 5 3 5 2 5 1 1 4 6 3]


3.58

- 강사님 해설 및 정답

In [ ]:
# 강사님 해답 중 추가 코드

In [11]:
# dice array에서의 고유값
np.unique(ex)

array([1, 2, 3, 4, 5, 6])

In [12]:
# dice array에서 고유값 및 그 갯수
np.unique(ex, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([16, 15, 15, 18, 21, 15], dtype=int64))

In [13]:
unique, counts = np.unique(ex, return_counts=True)
dict(zip(unique, counts))       # zip으로 dictionary 만들기 !

{1: 16, 2: 15, 3: 15, 4: 18, 5: 21, 6: 15}

8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인  표준 정규 분포를 따른다고 하자.   
250일 동안의 주가를 무작위로 생성하시오. 

In [14]:
# 주식 수익률과 기댓값 관계를 이해를 못해서 못풀었음...ㅠㅜ

- 강사님 해설 및 정답

In [ ]:
"""
if 10,000원 주식이 있다고 쳐보자.
1% 가 올라서 10,100원
다음날 -1% 된다면 ? 
(10,000원이 될 것 같지만...) 실제로는 ==> 10,100-101 = 9,999원이 되어버림 !!

==> 같은 비율로 오르고 내려가더라도 내려가는 것이 손해가 더 심함 ... ! 
""" 

In [15]:
# 5개만 먼저 테스트
np.random.seed(2022)                    # seed 고정값
rate = np.random.normal(0, 0.01, 5)     # 이자율 = rate / 0.01 ==> 수익률 0%, 표준편차 1% / 만약 randn으로 했으면 나중에 rate[i]에 * 0.01 해줘야 함 ~
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [16]:
# 위에서 구한 이자율(%)
rate * 100

array([-5.27899086e-04, -2.74901425e-01, -1.39285562e-01,  1.98468616e+00,
        2.82109326e-01])

In [17]:
# 250개 정규분포, 리스트 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [18]:
# 정규분포, 어레이 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [19]:
# 표준정규분포를 이용한 경우
np.random.seed(2022)
rate = np.random.randn(250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i]*0.01)
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])